name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight UTC
  workflow_dispatch:      # allows manual runs

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake SVG
        uses: InvalidLenni/README.md@Template
        with:
          github_user_name: brianali-codes
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push SVG
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist

